name: Darrell Stern
favicon: null
layout_spectrum: 0.29577137529850006
typography_spectrum: 0.689618939999491
title: Spiraling Upward
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.24765051249414682
  lightness: 0.5034066408406943
  saturation: 0.7467765887267888
  rhythmicContrast: 0.7796947446186095
purpose: []
